### ISSUE TITLE
Can't get any balance out of etc

### ISSUE THREAD

**Issue by MitsuraIvan** [xclud/web3dart#22]
E/flutter ( 9383): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError: Value not in range: 32
E/flutter ( 9383): #0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5075:5)
E/flutter ( 9383): #1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1917:5)
E/flutter ( 9383): #2      _IntTypeBase.decode (package:web3dart/src/contracts/abi/integers.dart:37:31)
E/flutter ( 9383): #3      TupleType.decode (package:web3dart/src/contracts/abi/tuple.dart:106:29)
E/flutter ( 9383): #4      ContractFunction.decodeReturnValues (package:web3dart/src/contracts/abi/abi.dart:273:30)
E/flutter ( 9383): #5      Web3Client.call (package:web3dart/src/core/client.dart:354:21)
E/flutter ( 9383): <asynchronous suspension>
E/flutter ( 9383): #6      Token.getBalance (package:untitled_flutter_test/presenter/model/token.dart:48:22)
E/flutter ( 9383): <asynchronous suspension>
E/flutter ( 9383): #7      TestPlay.test4 (package:untitled_flutter_test/presenter/model/testPlay.dart:93:21)
E/flutter ( 9383): <asynchronous suspension>

```
testEthWallet = BigInt.parse("110925170330547180589658713797469555526567670447166036968931513412325485042143");
testEthNet = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161";
web3client = Web3Client(testEthNet, Client());
credentials = EthPrivateKey.fromInt(testEthWallet);

usdtAddress = EthereumAddress.fromHex("0xdac17f958d2ee523a2206206994597c13d831ec7");
ownAddress = credentials.address;
chainID = await _web3client.getNetworkId();

//crash v1
    final erc20 = Erc20(
      address: usdtAddress,
      client: _web3client,
      chainId: chainID,
    );
    final balanceUsdt = await erc20.balanceOf(ownAddress);

//crash v2
    final token = Token(
       address: usdtAddress, 
       client: _web3client,
    );
    final balance = await token.getBalance(ownAddress);
```

Eth balance, aka, 
    final balance = await web3client.getBalance(ownAddress);
works great, but that's it. I'm really missing something here, because it looks like I'm the only one who have this issue today.

**Comment by HoangKimDuc** [comment]
+1 same issue

**Comment by jvinai** [comment]
I have a similar issue too.

**Comment by ketowk** [comment]
Any updates?

**Comment by MitsuraIvan** [comment]
@ketowk nope, you can switch to real network
